spring.application.name=EcommerceSpring
<<<<<<< HEAD
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username=root
spring.datasource.password=YourNewPassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#Speak SQL in the MySQL 8 accent
spring.jpa.hibernate.ddl-auto=update
#It tells Hibernate how to handle the database
# schema (tables, columns, etc.) every time your app starts.
#spring.jpa.hibernate.ddl-auto ? The setting that controls schema generation.
#
#update ? The mode that tells Hibernate to automatically update
# the database schema to match your entities (Java classes).
server.port=9000
spring.devtools.restart.enabled=false
=======
server.port=9000

spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username=root
spring.datasource.password=YourNewPassword
#this tells spring boot which jdbc driver class to use
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#tells to hibernate to print all the generates sql queries to console useful for debugging
#specifying the sql dialect hibernate should use
#ensures hiberanates generates sql optimised sql syntax without this springboot might guess based on jdbc url
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#Controls how hiberanate handles schema generation:
spring.jpa.hibernate.ddl-auto=update

# Show SQL statements
spring.jpa.show-sql=true

# Print SQL statements with parameters
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Optional: format SQL nicely
spring.jpa.properties.hibernate.format_sql=true


>>>>>>> cc1547424d8bc5977dc85e0cc1ab345802adebb0
